server:
  port: 8090

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  jpa:
    generate-ddl: true 
    database: default
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  data:
    mongodb:
      host: mongo
      port: 30001
      username: admin 
      password: admin123
      database: microservices
      uri: mongodb://admin:admin123@mongo:30001
      url: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:30001/${MONGODB_DB}
      #uri: mongodb://34.228.190.228:27017 # Mongo database URI. Cannot be set with host, port and credentials. 
  datasource:
    host: mongo
    port: 30001
    username: admin 
    password: admin123
    uri: mongodb://admin:admin123@mongo:30001
    url: mongodb://admin:admin123@mongo:30001/microservices
  cloud:
    kubernetes:
      secrets:
        enabled: true
        paths: /etc/mongo/config

# PostgreSQL DB - "postgres"
postgres:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=public 
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

# PostgreSQL DB - "postgres2"
postgres2:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES2_PORT}/${POSTGRES2_DB}?currentSchema=public 
    username: ${POSTGRES2_USER}
    password: ${POSTGRES2_PASSWORD}
    driver-class-name: org.postgresql.Driver


logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

# Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Because detection is disabled you have to set correct dialect by hand.
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

