server:
  port: 8090

spring:
  data:
    mongodb:
      host: localhost
      port: 30001
      username: admin 
      password: admin123
      uri: mongodb://admin:admin123@localhost:30001
  cloud:
    kubernetes:
      secrets:
        enabled: true
        paths: /etc/mongo/config

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
